-- resolver_snapshot — persist the EntityResolver attribution snapshot so
-- pet->owner links, kind classifications, user assertions, and evidence survive
-- a mid-file crash/restart (ARCHITECTURE.md ADR-5, DATA_MODEL.md §3).
--
-- INTERIM SCHEMA HOME (issue #19): this table is created idempotently at pipeline
-- init (ensureResolverSnapshotTable) with `CREATE TABLE IF NOT EXISTS` and is
-- deliberately kept OUT of the versioned migration chain / schema_migrations.
-- Rationale:
--   (1) Bumping the DB's schema_version past @eqlcc/database's central registry
--       value would make its migrate(db) — which knows only the base version —
--       REFUSE TO OPEN the DB as "newer than supported" (DATA_MODEL.md §1).
--   (2) A composed version 2 would collide with a future central 0002.
-- #20 will FORMALIZE this as a real numbered forward-only migration in the
-- central @eqlcc/database registry (per CLAUDE.md: every schema change is a
-- numbered migration). The `IF NOT EXISTS` DDL makes that relocation a no-op.
--
-- Home rationale (DATA_MODEL.md §3): the resolver snapshot is a single JSON blob
-- per tracked log file. It is a rebuildable CACHE of resolver state, NOT a source
-- of truth — `events` remains the source of truth and the snapshot can be
-- regenerated by replaying events through a fresh resolver (so a stale-version
-- row is safely discarded, see loadResolverSnapshot). entities/entity_links are
-- the eventual PROJECTION of this state (a projection writer is #20, out of scope
-- here), so a dedicated single-row store is the simplest correct interim home.
CREATE TABLE IF NOT EXISTS resolver_snapshot (
  log_file_id INTEGER PRIMARY KEY REFERENCES log_files(id),  -- one snapshot per tracked file
  version     INTEGER NOT NULL,                              -- ResolverSnapshot.version (schema tag; gates load)
  snapshot    TEXT NOT NULL,                                 -- JSON ResolverSnapshot (serialized)
  updated_at  INTEGER NOT NULL                               -- unix ms of last write
);
