/**
 * Spell/ability emote dictionaries — eql-beta-2026-07.
 *
 * Emote wording comes from spell data, so there is NO general pattern to
 * exploit; recognizing them generically would mean inventing formats. Instead,
 * every entry below is a captured line (or captured suffix) from the July 2026
 * beta corpus (434k lines), included when observed ≥ ~10 times. New emotes
 * surface as raw_unknown shapes and are promoted here with fixtures.
 */

/** Second-person / subject-less emote lines, matched exactly. */
export const SELF_SPELL_EMOTES: readonly string[] = [
  "You feel your life force drain away.",
  "A burst of strength surges through your body.",
  "You whistle an ancient warsong.",
  "Your wounds begin to heal.",
  "You feel better.",
  "You have been diseased.",
  "You feel much better.",
  "You writhe in the grip of agony.",
  "You feel a little better.",
  "You have been poisoned.",
  "You have been lacerated.",
  "Your stomach begins to cramp.",
  "You are no longer diseased.",
  "Your stomach feels better.",
  "Your feet come free.",
  "The poison has run its course.",
  "You feel your skin freeze.",
  "Your feet adhere to the ground.",
  "You are struck by a sudden force.",
  "You are slashed by shards of ice.",
  "The darkness fades.",
  "You are surrounded by darkness.",
  "Your feet sink into the ground.",
  "You feel your strength grow.",
  "You slow down as your feet are covered in tangling weeds.",
  "The tangling weeds wither away.",
  "You feel your skin ignite.",
  "You are in the grip of darkness.",
  "You feel a traveling spirit enter you.",
  "The spirit of travel leaves you.",
  "You feel your strength return.",
  "Your skin cools.",
  "You feel your skin blister and burn.",
  "You are struck by a sudden burst of force.",
  "You feel stronger.",
  "Your legs feel weak.",
  "You are shrouded by anti-life magic.",
  "The shroud fades.",
  "Your feet move faster.",
  "You feel a surge of strength as you let forth a mighty yaulp.",
  "You feel protected from poison.",
  "Your body spasms as the lightning bolt arcs through you.",
  "You feel your skin smolder.",
  "A brilliant blue aura surrounds your weapon.",
  "You feel somewhat vulnerable.",
  "You feel protected from cold.",
  "Strength returns to your legs.",
  "You feel dexterous.",
  "You feel a healing touch.",
  "You feel the favor of the gods upon you.",
  "You feel your skin singe as the Burst of Fire hits you.",
  "You feel more agile.",
  "Your strength fades.",
  "You feel your skin singe as the Burst of Flame hits you.",
  "You feel a rush of courage.",
  "Your stolen strength fades.",
  "Your blood simmers.",
  "You feel a shadow pass over you.",
  "You feel magnanimous of spirit.",
  "A mystical path appears before you.",
  "You slow down.",
  "You stagger as spirits of frost slam against you.",
  "You feel protected from fire.",
  "You feel the spirit of wolf enter you.",
  "You are as quiet as a herd of running elephants.",
  "Your vulnerability fades.",
  "You feel the spirit of bear enter you.",
  "Your blood cools.",
  "You are engulfed by darkness.",
  "The barking fades.",
  "The vortex of shadows fades.",
  "You feel protected from disease.",
  "Your brain begins to smolder.",
  "You feel a shortness of breath.",
  "You feel your body pulse with energy.",
  "You feel the spirit of snake enter you.",
  "You can breathe again.",
  "You feel smaller.",
  "You are surrounded by flickering flames.",
  "You are chilled by a bolt of frost.",
  "Your feet become entwined.",
  "You have been struck down by wrath.",
  "The jig sends energy zinging through your body.",
  "Your eyes tingle.",
  "Your skin becomes as hard as turtle shell.",
  "The flames are extinguished.",
  "You speed back up.",
  "You feel your blood begin to leech away.",
  "You feel drowsy.",
  "You feel less drowsy.",
  "You have been struck.",
  "You feel your skin burn as poison seeps through your skin.",
  "You feel armored.",
  "You feel no need to breathe.",
  "You feel less courageous.",
  "You are enveloped by flame.",
  "Your hand begins to glow.",
  "You resume breathing.",
  "You grow scales.",
  "The flames die down.",
  "You are conscious again!",
  "The roots fall from your feet.",
  "A dull aura covers your hand.",
  "You have been sprayed with skunk musk.",
  "You no longer smell of skunk.",
  "You feel your health begin to drain away.",
];

/**
 * Third-person emote suffixes: `<subject><suffix>` where `<subject>` is a
 * name-shaped prefix. More-specific suffixes must precede their generic
 * overlaps (e.g. "… frost rift." before " is struck.").
 */
export const SUBJECT_EMOTE_SUFFIXES: readonly string[] = [
  " staggers as spirits of frost slam against them.",
  " staggers as a dagger of frost slams into them.",
  " staggers.",
  " feels a little better.",
  " feels much better.",
  " feels better.",
  " doubles over in pain.",
  " is struck by the frost rift.",
  " is struck by a sudden burst of force.",
  " is struck by a sudden force.",
  " is struck.",
  " pales.",
  " winces.",
  " looks courageous.",
  "'s skin turns hard as wood.",
  " is enveloped by flame.",
  " is surrounded by a thorny barrier.",
  " is surrounded by a translucent shield.",
  " is surrounded by a brief lupine aura.",
  " is surrounded by darkness.",
  " animates an undead servant.",
  "'s body pulses with energy.",
  " is bathed in fire.",
  " is tortured by the condemnation of Rodcet Nife.",
  "'s wounds fester.",
  " begins to bleed profusely!",
  " singes as the Burst of Flame hits them.",
  " singes as the Burst of Fire hits them.",
  " is covered in flames.",
  " hisses and strikes!",
  " clatters as it turns towards you.",
  " has been poisoned.",
  " has been smitten.",
  "'s skin looks like leather.",
  "'s skin freezes.",
  "'s voice booms.",
  " rages.",
  " has fallen to the ground.",
  " weakens.",
  " begins to mend.",
  " is bound by strands of solid music.",
  " is lost in a fit of despair.",
  " is slashed by shards of ice.",
  " screams as poison burns their veins!",
  " is protected by a vortex of shadows.",
  " is enveloped in blazing energy.",
  " is pelted by an ancient blizzard.",
  " fades away.",
  " yawns.",
  " writhes in the grip of agony.",
  "'s corpse splinters into hundreds of tiny bone fragments.",
  " suffers a blow to the head.",
  "'s corpse crumples to the ground.",
  "'s skin goes numb.",
  "'s skin turns hard as stone.",
  " is cloaked in a shimmer of glowing symbols.",
  " feels much faster.",
  " looks brave.",
  "'s limbs move slower!",
  "'s wounds turn black.",
  " adheres to the ground.",
  " is stunned by scintillating colors.",
  "'s corpse clicks a few times then ceases struggling.",
  " resumes his patrol, his keyring jangling noisily at his side.",
  " is chilled by a bolt of frost.",
  "'s corpse rolls over letting out its last breath as it falls victim to its mortal wounds.",
  "'s corpse shudders and collapses.",
  "'s corpse lashes out at its attacker one last time.",
  "'s corpse slows its spinning until it eventually disappears entirely.",
  "'s corpse dissipates as it hits the ground.",
  "'s corpse falls to the ground as its wings give out.",
  "'s corpse hisses as it coils lifelessly to the ground.",
  "'s corpse stops moving.",
];
