/**
 * System/UI message dictionary — eql-beta-2026-07.
 *
 * Closed, fixture-backed set: every entry is a captured corpus line (July 2026
 * beta, 434k-line benchmark), included when observed ≥ ~10 times. `kind` is the
 * stable machine name recorded on the emitted `system_message` event.
 */

export const SYSTEM_EXACT_MESSAGES: ReadonlyArray<readonly [kind: string, text: string]> = [
  ["auto_attack_on", "Auto attack is on."],
  ["auto_attack_off", "Auto attack is off."],
  ["target_too_far", "Your target is too far away, get closer!"],
  ["target_out_of_range", "Your target is out of range, get closer!"],
  ["stunned", "You are stunned!"],
  ["stun_worn", "You are no longer stunned."],
  ["stun_overcome", "You overcome the stun!"],
  ["cast_while_stunned", "You can't cast spells while stunned!"],
  ["cast_while_invulnerable", "You can't cast spells while invulnerable!"],
  ["cannot_see_target", "You cannot see your target."],
  ["already_have_attention", "You already have your target's attention."],
  ["insufficient_mana", "Insufficient Mana to cast this spell!"],
  ["no_target", "You no longer have a target."],
  ["encounter_locked", "Your attack failed because your target is Encounter Locked to someone else."],
  ["loot_no_room", "You cannot loot this item no room in your inventory."],
  ["must_click_target", "You must first click on the being you wish to attack!"],
  ["must_select_spell_target", "You must first select a target for this spell!"],
  ["loading", "LOADING, PLEASE WAIT..."],
  ["out_of_ammo", "You have run out of ammo!"],
  ["cant_hit_from_here", "You can't hit them from here."],
  ["disarm_failed", "Your attempt to disarm failed."],
  ["disarm_too_far", "You are too far away to disarm. Get closer."],
  ["mend", "You mend your wounds and heal some damage."],
  ["bandage_begin", "You begin to bandage yourself."],
  ["bandage_complete", "The bandaging is complete."],
  ["not_assigned_adventure", "You are not currently assigned to an adventure."],
  ["taunt_no_npc", "You must target an NPC to taunt first."],
  ["taunt_too_far", "You are too far away from your target to taunt."],
  ["spellbook_updated", "Your spellbook has been updated!"],
  ["camp_prepare", "It will take you about 30 seconds to prepare your camp."],
  ["missing_components", "You are missing some required components."],
  ["sneak_begin", "You begin to sneak..."],
  ["hide_begin", "You begin to hide..."],
  ["hide_failed", "You failed to hide yourself."],
  ["no_longer_hidden", "You are no longer hidden."],
  ["bash_no_shield", "You need to equip a shield in order to BASH"],
  ["marketplace_unavailable", "The Marketplace is unavailable at this time. Please try again later."],
  ["knocked_unconscious", "You have been knocked unconscious!"],
  ["encumbered", "You are encumbered!"],
  ["not_encumbered", "You are no longer encumbered."],
  ["attack_self_hint", "Try attacking someone other than yourself. It's more productive."],
  ["command_unavailable", "You can't use that command right now..."],
  ["action_retry", "You cannot perform that action right now. Please try again in a moment."],
  ["consider_whom", "Consider whom?"],
  ["zone_safe_point", "Returning to Zone Safe Point. Please wait..."],
  ["welcome", "Welcome to EverQuest Legends!"],
  ["locked_no_key", "It's locked and you're not holding the key."],
  ["song_blocked_symphonic", "This song cannot be played while Symphonic Aura is enabled."],
  ["cannot_change_stance", "You cannot change stances yet."],
  ["bandage_no_bandages", "You can't bandage without bandages, go buy some."],
  ["forage_fail", "You fail to locate any food nearby."],
  ["scribe_stack", "You cannot scribe a stack of spells, please use only one of that scroll to scribe."],
  ["find_blocked", "Mysterious forces prevent you from finding your destination easily."],
  ["merge_mismatch", "The item you are trying to add will not work, you cannot merge two different types of items."],
  ["must_stand_attack", "You must be standing to attack!"],
  ["disarm_no_target", "You must target someone to disarm first."],
  ["afk_on", "You are now A.F.K. (Away From Keyboard)."],
  ["no_tell_to_reply", "You have not received any tells, so you cannot reply."],
  [
    "map_zoom_notice",
    'Manually zooming and panning is disabled when the map is in Find mode and the "Auto-Zoom" button is active.  If you wish to manually adjust the map while in Find mode, then uncheck the "Auto-Zoom" button or use the right click re-center.',
  ],
  [
    "help_hint",
    'If you need help, click on the EQ Menu button at the bottom of your screen and select the "Help" option.',
  ],
];
