-- 0002_resolver_snapshot — persist the EntityResolver attribution snapshot so
-- pet->owner links, kind classifications, user assertions, and evidence survive
-- a mid-file crash/restart (ARCHITECTURE.md ADR-5, DATA_MODEL.md §3).
--
-- Forward-only migration (ADR-7): no down migration. Applied inside a single
-- transaction by @eqlcc/database's migrate() runner and recorded in
-- schema_migrations, exactly like the base schema (0001_init).
--
-- Ownership note (issue #19): this migration is COMPOSED onto the base
-- migration set via migrate({ migrations }) by the orchestrator rather than
-- registered in @eqlcc/database's own MIGRATION_FILES registry. That keeps the
-- change inside packages/orchestrator/** and avoids editing @eqlcc/database's
-- version-pinned tests, which the orchestrator does not own. When the
-- data-engineer next touches the central registry (#20), this table should be
-- consolidated there as the canonical 0002. `CREATE TABLE IF NOT EXISTS` keeps
-- that future relocation idempotent.
--
-- Home rationale (DATA_MODEL.md §3): the resolver snapshot is a single JSON blob
-- per tracked log file. It is a rebuildable cache of resolver state, NOT a new
-- source of truth — `events` remains the source of truth and the snapshot can be
-- regenerated by replaying events through a fresh resolver. entities/entity_links
-- are the eventual PROJECTION of this state (a projection writer is #20, out of
-- scope here), so a dedicated single-row store is the simplest correct home for
-- M1 and does not pre-empt that projection work.
CREATE TABLE IF NOT EXISTS resolver_snapshot (
  log_file_id INTEGER PRIMARY KEY REFERENCES log_files(id),  -- one snapshot per tracked file
  version     INTEGER NOT NULL,                              -- ResolverSnapshot.version (schema tag)
  snapshot    TEXT NOT NULL,                                 -- JSON ResolverSnapshot (serialized)
  updated_at  INTEGER NOT NULL                               -- unix ms of last write
);
